# Sprint 9
Sloovik/java-filmorate pull request #2
Opened 2023-06-08 11:16 UTC by Sloovik

2023-06-15 09:51 UTC, Sloovik commented
Первое задание по проекту filmorate

2023-06-16 07:42 UTC, ErkinKasymaliev requested changes
привет, отличная работа!
Оставил пару комментов. Коммент в FilmController - рекомендательный

2023-06-16 07:42 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/repository/FilmRepository.java
> +public class FilmRepository {
чуть вперед забежали, но все ок, отлично!

2023-06-16 07:42 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/validation/ReleaseDateConstraint.java
> +public @interface ReleaseDateConstraint {
отлично!

2023-06-16 07:42 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        log.info("Create movie: {} - Finished", film);
так логи писать не надо, потому что такие логи обычно избыточны. Понять можно по статусу ответа, обычно  200 или 204. В каждом методе контроллера можете поставить логи, например, Get request to create film, и тело request body

2023-06-16 07:42 UTC, ErkinKasymaliev commented on src/test/java/ru/yandex/practicum/filmorate/model/FilmTest.java
> +
добавьте еще кейс где все валидации прошли успешно

2023-06-16 07:42 UTC, ErkinKasymaliev commented on src/test/java/ru/yandex/practicum/filmorate/model/UserTest.java
> +
добавьте еще кейс где все валидации прошли успешно

2023-06-16 09:21 UTC, Sloovik commented on src/test/java/ru/yandex/practicum/filmorate/model/FilmTest.java
> +
Имеется в виду, что валидация не потребовалась? Или тест на совокупность тестов валидации, не очень понял)

2023-06-16 09:21 UTC, Sloovik commented on src/test/java/ru/yandex/practicum/filmorate/model/FilmTest.java
> +
> добавьте еще кейс где все валидации прошли успешно

Имеется в виду, что валидация не потребовалась? Или тест на совокупность тестов валидации, не очень понял)

2023-06-19 09:45 UTC, ErkinKasymaliev approved these changes
привет, работа принята!

2023-06-21 08:20 UTC, merged